import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { isDefaultPostEffect } from '../shared/defaultEffectPlacement.ts';
import { RIG_PRESET_CATALOG } from '../shared/rigPresetCatalog.ts';
import { AMP_CATEGORIES } from '../src/audio/ampCategories.ts';
import { AMP_REGISTRY } from '../src/audio/amps.ts';
import { CAB_REGISTRY } from '../src/audio/cabs.ts';
import { EFFECT_REGISTRY } from '../src/audio/effects/index.ts';

const params = (definition: { params: Array<{
  key: string;
  min: number;
  max: number;
  defaultValue: number;
}> }) => definition.params.map(({ key, min, max, defaultValue }) => ({
  key,
  min,
  max,
  defaultValue,
}));

test('browser-neutral Rig catalog stays aligned with interactive audio registries', () => {
  assert.deepEqual(RIG_PRESET_CATALOG, {
    effects: EFFECT_REGISTRY.map((definition) => ({
      id: definition.id,
      params: params(definition),
      defaultPost: isDefaultPostEffect(definition.id),
    })),
    amps: AMP_REGISTRY.map((definition) => ({
      id: definition.id,
      params: params(definition),
    })),
    cabs: CAB_REGISTRY.map((definition) => ({
      id: definition.id,
      params: params(definition),
    })),
    ampModels: AMP_CATEGORIES.flatMap((category) => category.models.map((model) => ({
      key: model.key,
      categoryId: category.id,
      ampId: model.kind === 'builtin' ? model.ref : 'nam-wasm',
    }))),
    ampCategoryIds: AMP_CATEGORIES.map((category) => category.id),
    defaults: {
      ampModelKey: 'builtin:crunch',
      cabId: 'gb4x12',
      inputGain: 1,
      masterVolume: 0.5,
    },
  });
});

test('server publication seam does not import browser runtime or persistence modules', async () => {
  const [catalogSource, publicationSource, packageSource] = await Promise.all([
    readFile(new URL('../shared/rigPresetCatalog.ts', import.meta.url), 'utf8'),
    readFile(new URL('../shared/publishableRig.ts', import.meta.url), 'utf8'),
    readFile(new URL('../package.json', import.meta.url), 'utf8'),
  ]);

  assert.doesNotMatch(catalogSource, /from ['"]\.\.\/src\/(audio|state\/store)/);
  assert.doesNotMatch(publicationSource, /from ['"]\.\.\/src\/(audio|state\/store)/);
  assert.doesNotMatch(`${catalogSource}\n${publicationSource}`, /\b(?:localStorage|AudioContext)\b/);
  assert.match(catalogSource, /GENERATED by/);
  assert.match(packageSource, /check:rig-catalog/);
});
