import type { RigPresetCatalog } from '../src/state/presetCodec.ts';

/**
 * GENERATED by `npm run generate:rig-catalog`. Do not edit by hand.
 * This checked-in pure-data artifact keeps server validation browser-neutral.
 */
export const RIG_PRESET_CATALOG: RigPresetCatalog = {
  "effects": [
    {
      "id": "noiseGate",
      "params": [
        {
          "key": "threshold",
          "min": -90,
          "max": 0,
          "defaultValue": -50
        },
        {
          "key": "attack",
          "min": 0.001,
          "max": 0.05,
          "defaultValue": 0.005
        },
        {
          "key": "release",
          "min": 0.01,
          "max": 0.5,
          "defaultValue": 0.08
        }
      ],
      "defaultPost": false
    },
    {
      "id": "whammy",
      "params": [
        {
          "key": "position",
          "min": 0,
          "max": 100,
          "defaultValue": 0
        },
        {
          "key": "range",
          "min": -2,
          "max": 2,
          "defaultValue": 2
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "compressor",
      "params": [
        {
          "key": "threshold",
          "min": -60,
          "max": 0,
          "defaultValue": -24
        },
        {
          "key": "ratio",
          "min": 1,
          "max": 20,
          "defaultValue": 4
        },
        {
          "key": "attack",
          "min": 0,
          "max": 100,
          "defaultValue": 10
        },
        {
          "key": "release",
          "min": 10,
          "max": 1000,
          "defaultValue": 250
        },
        {
          "key": "makeup",
          "min": 0,
          "max": 12,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "la2a",
      "params": [
        {
          "key": "reduction",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        },
        {
          "key": "gain",
          "min": 0,
          "max": 30,
          "defaultValue": 0
        },
        {
          "key": "mode",
          "min": 0,
          "max": 1,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "fet1176",
      "params": [
        {
          "key": "threshold",
          "min": -60,
          "max": 0,
          "defaultValue": -20
        },
        {
          "key": "ratio",
          "min": 0,
          "max": 4,
          "defaultValue": 1
        },
        {
          "key": "attack",
          "min": 20,
          "max": 800,
          "defaultValue": 200
        },
        {
          "key": "release",
          "min": 50,
          "max": 1100,
          "defaultValue": 250
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "dynacomp",
      "params": [
        {
          "key": "sensitivity",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "klon",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -19.5
        }
      ],
      "defaultPost": false
    },
    {
      "id": "overdrive",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "tone",
          "min": 500,
          "max": 8000,
          "defaultValue": 3000
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -19
        }
      ],
      "defaultPost": false
    },
    {
      "id": "ts808",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 100,
          "defaultValue": 45
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -11
        }
      ],
      "defaultPost": false
    },
    {
      "id": "ts808wdf",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 100,
          "defaultValue": 45
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "klonwdf",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "ratwdf",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "filter",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "ds1wdf",
      "params": [
        {
          "key": "dist",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "fuzzfacewdf",
      "params": [
        {
          "key": "fuzz",
          "min": 0,
          "max": 100,
          "defaultValue": 70
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "bigmuffwdf",
      "params": [
        {
          "key": "sustain",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "distortion",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "tone",
          "min": 500,
          "max": 8000,
          "defaultValue": 2500
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -18
        }
      ],
      "defaultPost": false
    },
    {
      "id": "rat",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "filter",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -19.5
        }
      ],
      "defaultPost": false
    },
    {
      "id": "fuzz",
      "params": [
        {
          "key": "fuzz",
          "min": 0,
          "max": 100,
          "defaultValue": 65
        },
        {
          "key": "tone",
          "min": 400,
          "max": 6000,
          "defaultValue": 2200
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -18
        }
      ],
      "defaultPost": false
    },
    {
      "id": "autowah",
      "params": [
        {
          "key": "sens",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "freq",
          "min": 150,
          "max": 1200,
          "defaultValue": 400
        },
        {
          "key": "reso",
          "min": 1,
          "max": 12,
          "defaultValue": 6
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 100
        }
      ],
      "defaultPost": false
    },
    {
      "id": "crybabywdf",
      "params": [
        {
          "key": "position",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "wahpedal",
      "params": [
        {
          "key": "position",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "reso",
          "min": 50,
          "max": 200,
          "defaultValue": 100
        },
        {
          "key": "level",
          "min": 0,
          "max": 200,
          "defaultValue": 100
        }
      ],
      "defaultPost": false
    },
    {
      "id": "eq",
      "params": [
        {
          "key": "low",
          "min": -15,
          "max": 15,
          "defaultValue": 0
        },
        {
          "key": "mid",
          "min": -15,
          "max": 15,
          "defaultValue": 0
        },
        {
          "key": "high",
          "min": -15,
          "max": 15,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "chorus",
      "params": [
        {
          "key": "rate",
          "min": 0.1,
          "max": 5,
          "defaultValue": 0.8
        },
        {
          "key": "depth",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        }
      ],
      "defaultPost": false
    },
    {
      "id": "flanger",
      "params": [
        {
          "key": "rate",
          "min": 0.1,
          "max": 2,
          "defaultValue": 0.3
        },
        {
          "key": "depth",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "feedback",
          "min": 0,
          "max": 95,
          "defaultValue": 50
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        }
      ],
      "defaultPost": false
    },
    {
      "id": "phaser",
      "params": [
        {
          "key": "rate",
          "min": 0.1,
          "max": 5,
          "defaultValue": 0.5
        },
        {
          "key": "depth",
          "min": 0,
          "max": 100,
          "defaultValue": 70
        }
      ],
      "defaultPost": false
    },
    {
      "id": "tremolo",
      "params": [
        {
          "key": "rate",
          "min": 0.5,
          "max": 10,
          "defaultValue": 5
        },
        {
          "key": "depth",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        }
      ],
      "defaultPost": false
    },
    {
      "id": "delay",
      "params": [
        {
          "key": "time",
          "min": 50,
          "max": 2000,
          "defaultValue": 400
        },
        {
          "key": "feedback",
          "min": 0,
          "max": 90,
          "defaultValue": 35
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        }
      ],
      "defaultPost": true
    },
    {
      "id": "analogdelay",
      "params": [
        {
          "key": "time",
          "min": 20,
          "max": 600,
          "defaultValue": 300
        },
        {
          "key": "feedback",
          "min": 0,
          "max": 95,
          "defaultValue": 40
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "mod",
          "min": 0,
          "max": 100,
          "defaultValue": 0
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        }
      ],
      "defaultPost": true
    },
    {
      "id": "tapedelay",
      "params": [
        {
          "key": "time",
          "min": 50,
          "max": 1000,
          "defaultValue": 400
        },
        {
          "key": "feedback",
          "min": 0,
          "max": 110,
          "defaultValue": 40
        },
        {
          "key": "wow",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        },
        {
          "key": "saturation",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        }
      ],
      "defaultPost": true
    },
    {
      "id": "pingpong",
      "params": [
        {
          "key": "time",
          "min": 50,
          "max": 1500,
          "defaultValue": 400
        },
        {
          "key": "feedback",
          "min": 0,
          "max": 90,
          "defaultValue": 40
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        }
      ],
      "defaultPost": true
    },
    {
      "id": "reverb",
      "params": [
        {
          "key": "time",
          "min": 0.5,
          "max": 6,
          "defaultValue": 2.5
        },
        {
          "key": "decay",
          "min": 1,
          "max": 6,
          "defaultValue": 2.5
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        }
      ],
      "defaultPost": true
    },
    {
      "id": "springreverb",
      "params": [
        {
          "key": "time",
          "min": 1,
          "max": 4,
          "defaultValue": 2
        },
        {
          "key": "dwell",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "tone",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        }
      ],
      "defaultPost": true
    },
    {
      "id": "plate",
      "params": [
        {
          "key": "time",
          "min": 0.5,
          "max": 6,
          "defaultValue": 2.5
        },
        {
          "key": "damp",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "preDelay",
          "min": 0,
          "max": 100,
          "defaultValue": 0
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        }
      ],
      "defaultPost": true
    },
    {
      "id": "shimmer",
      "params": [
        {
          "key": "time",
          "min": 2,
          "max": 8,
          "defaultValue": 4.5
        },
        {
          "key": "shimmer",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "damp",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "mix",
          "min": 0,
          "max": 100,
          "defaultValue": 35
        }
      ],
      "defaultPost": true
    },
    {
      "id": "volume",
      "params": [
        {
          "key": "level",
          "min": -60,
          "max": 6,
          "defaultValue": 0
        },
        {
          "key": "pan",
          "min": -50,
          "max": 50,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namComp",
      "params": [
        {
          "key": "threshold",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "ratio",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "attack",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "release",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namTs",
      "params": [
        {
          "key": "drive",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "tone",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namRat",
      "params": [
        {
          "key": "distortion",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "filter",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namDs1",
      "params": [
        {
          "key": "dist",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "tone",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namFf",
      "params": [
        {
          "key": "fuzz",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namGr",
      "params": [
        {
          "key": "sustain",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "tone",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namMxr",
      "params": [
        {
          "key": "distortion",
          "min": 0,
          "max": 1,
          "defaultValue": 0.5
        },
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namSd1",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namFortin",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "namKlone",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    },
    {
      "id": "tone3000Nam",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ],
      "defaultPost": false
    }
  ],
  "amps": [
    {
      "id": "clean",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 45
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 65
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -14.5
        }
      ]
    },
    {
      "id": "crunch",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 65
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -20.5
        }
      ]
    },
    {
      "id": "recto",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 70
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -20
        }
      ]
    },
    {
      "id": "chime",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 45
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 65
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 65
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -19.5
        }
      ]
    },
    {
      "id": "wdfchamp",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -6
        }
      ]
    },
    {
      "id": "wdfbogner",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -6
        }
      ]
    },
    {
      "id": "wdftwin",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -6
        },
        {
          "key": "bright",
          "min": 0,
          "max": 100,
          "defaultValue": 20
        }
      ]
    },
    {
      "id": "wdfac30",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 30
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 55
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ]
    },
    {
      "id": "wdfjc120",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 40
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 60
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": -6
        },
        {
          "key": "chorus",
          "min": 0,
          "max": 1,
          "defaultValue": 0
        }
      ]
    },
    {
      "id": "nam-wasm",
      "params": [
        {
          "key": "gain",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "bass",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "mid",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "treble",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "presence",
          "min": 0,
          "max": 100,
          "defaultValue": 50
        },
        {
          "key": "master",
          "min": -30,
          "max": 6,
          "defaultValue": 0
        }
      ]
    }
  ],
  "cabs": [
    {
      "id": "open1x12",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -1
        }
      ]
    },
    {
      "id": "blue2x12",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -1.5
        }
      ]
    },
    {
      "id": "gb4x12",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -2
        }
      ]
    },
    {
      "id": "v304x12",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -2
        }
      ]
    },
    {
      "id": "customIr",
      "params": [
        {
          "key": "level",
          "min": -30,
          "max": 6,
          "defaultValue": -2
        }
      ]
    }
  ],
  "ampModels": [
    {
      "key": "builtin:clean",
      "categoryId": "clean",
      "ampId": "clean"
    },
    {
      "key": "builtin:wdfchamp",
      "categoryId": "clean",
      "ampId": "wdfchamp"
    },
    {
      "key": "builtin:wdftwin",
      "categoryId": "clean",
      "ampId": "wdftwin"
    },
    {
      "key": "builtin:wdfjc120",
      "categoryId": "clean",
      "ampId": "wdfjc120"
    },
    {
      "key": "nam-wasm-pack:bassman-sweep",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:fender-twinverb",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:wavenet-deluxe",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:peavey-5152-clean",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:deluxe-3x24",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:lstm-demo",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:ref-2x16",
      "categoryId": "clean",
      "ampId": "nam-wasm"
    },
    {
      "key": "builtin:chime",
      "categoryId": "chime",
      "ampId": "chime"
    },
    {
      "key": "builtin:wdfac30",
      "categoryId": "chime",
      "ampId": "wdfac30"
    },
    {
      "key": "nam-wasm:wavenet-ac10",
      "categoryId": "chime",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:vox-ac15",
      "categoryId": "chime",
      "ampId": "nam-wasm"
    },
    {
      "key": "builtin:crunch",
      "categoryId": "crunch",
      "ampId": "crunch"
    },
    {
      "key": "nam-wasm:jcm2000-clean",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:jcm2000-crunch",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm-pack:jcm800-sweep",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm-pack:dualterror-sweep",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:bug1990-lead",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:sovtek-mig50",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:orange-rockerverb",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:laney-gh100s",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:friedman-shirley-clean",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:boss-1x16",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:boss-2x16",
      "categoryId": "crunch",
      "ampId": "nam-wasm"
    },
    {
      "key": "builtin:recto",
      "categoryId": "recto",
      "ampId": "recto"
    },
    {
      "key": "builtin:wdfbogner",
      "categoryId": "recto",
      "ampId": "wdfbogner"
    },
    {
      "key": "nam-wasm-pack:evh-green-sweep",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm-pack:recto-red-sweep",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:jcm900-g12",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:jcm900-g16",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:5150-blockletter",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    },
    {
      "key": "nam-wasm:6505-red",
      "categoryId": "recto",
      "ampId": "nam-wasm"
    }
  ],
  "ampCategoryIds": [
    "clean",
    "chime",
    "crunch",
    "recto",
    "tone3000"
  ],
  "defaults": {
    "ampModelKey": "builtin:crunch",
    "cabId": "gb4x12",
    "inputGain": 1,
    "masterVolume": 0.5
  }
};
