import { readFile, writeFile } from 'node:fs/promises';
import { isDefaultPostEffect } from '../shared/defaultEffectPlacement.ts';
import type { RigPresetCatalog } from '../src/state/presetCodec.ts';
import { AMP_CATEGORIES } from '../src/audio/ampCategories.ts';
import { AMP_REGISTRY } from '../src/audio/amps.ts';
import { CAB_REGISTRY } from '../src/audio/cabs.ts';
import { EFFECT_REGISTRY } from '../src/audio/effects/index.ts';

const target = new URL('../shared/rigPresetCatalog.ts', import.meta.url);

const params = (definition: { params: Array<{
  key: string;
  min: number;
  max: number;
  defaultValue: number;
}> }) => definition.params.map(({ key, min, max, defaultValue }) => ({
  key,
  min,
  max,
  defaultValue,
}));

const catalog: RigPresetCatalog = {
  effects: EFFECT_REGISTRY.map((definition) => ({
    id: definition.id,
    params: params(definition),
    defaultPost: isDefaultPostEffect(definition.id),
  })),
  amps: AMP_REGISTRY.map((definition) => ({
    id: definition.id,
    params: params(definition),
  })),
  cabs: CAB_REGISTRY.map((definition) => ({
    id: definition.id,
    params: params(definition),
  })),
  ampModels: AMP_CATEGORIES.flatMap((category) => category.models.map((model) => ({
    key: model.key,
    categoryId: category.id,
    ampId: model.kind === 'builtin' ? model.ref : 'nam-wasm',
  }))),
  ampCategoryIds: AMP_CATEGORIES.map((category) => category.id),
  defaults: {
    ampModelKey: 'builtin:crunch',
    cabId: 'gb4x12',
    inputGain: 1,
    masterVolume: 0.5,
  },
};

const source = `import type { RigPresetCatalog } from '../src/state/presetCodec.ts';

/**
 * GENERATED by \`npm run generate:rig-catalog\`. Do not edit by hand.
 * This checked-in pure-data artifact keeps server validation browser-neutral.
 */
export const RIG_PRESET_CATALOG: RigPresetCatalog = ${JSON.stringify(catalog, null, 2)};
`;

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8');
  if (current !== source) {
    console.error('Rig preset catalog is stale. Run `npm run generate:rig-catalog`.');
    process.exitCode = 1;
  } else {
    console.log('Rig preset catalog is up to date.');
  }
} else {
  await writeFile(target, source, 'utf8');
  console.log('Generated shared/rigPresetCatalog.ts.');
}
